Repository GoodPointt/mutahae-proj, pull requests merged in 2024-02, with the labels that each got.

#83 refactor: split api calls and auth actions logic
  app/lib/api/auth.js
  app/lib/api/createUserStorages.js
  app/lib/authActions.js
  app/lib/locales/en.json
  app/lib/locales/he.json
  app/ui/auth/ClientSideRedirection.jsx
  app/ui/auth/LoginForm.jsx
  app/ui/auth/RecoveryForm.jsx
  app/ui/auth/RegisterForm.jsx
  app/ui/auth/ResetPasswordForm.jsx
Labels: fix

#84 fix: auth forms validation errors
  app/[lang]/auth/recovery/page.jsx
  app/lib/authActions.js
  app/ui/auth/RegisterForm.jsx
  app/ui/auth/ResetPasswordForm.jsx
Labels: fix

#88 fix: edit handling is user auth
  app/lib/actions.js
  app/ui/bag/Bag.jsx
  app/ui/header/Header.jsx
  app/ui/header/headerWrapper/HeaderWrapper.jsx
  app/ui/header/mobileMenu/profileMenu/ProfileMenu.jsx
  app/ui/header/topBar/TopBar.jsx
  app/ui/header/topMenu/TopMenu.jsx
  app/ui/productCard/ProductCard.jsx
Labels: fix

#89 feat: update header, footer, refactor catalog
  app/[lang]/layout.js
  app/ui/contactsList/ContactsList.jsx
  app/ui/footer/Footer.jsx
  app/ui/footer/contactsFooter/ContactsFooter.jsx
  app/ui/footer/footerProductsList/ProductsList.jsx
  app/ui/footer/footerWrapper/FooterWrapper.jsx
  app/ui/header/Header.jsx
  app/ui/header/headerWrapper/HeaderWrapper.jsx
  app/ui/header/mobileMenu/MobileMenu.css
  app/ui/header/mobileMenu/MobileMenu.jsx
  app/ui/header/mobileMenu/profileMenu/ProfileMenu.jsx
  app/ui/header/toolBar/ToolBar.jsx
  app/ui/localeSwitcher/LocaleSwitcher.jsx
  app/ui/paginationDisplay/PaginationDisplay.jsx
  app/ui/productsGrid/ProductsGrid.jsx
  app/ui/productsGrid/categoryMenu/CategoryMenu.jsx
  app/ui/productsGrid/filter/Filter.jsx
  app/ui/skeletons/SkeletonProducts.jsx
  app/ui/skeletons/SkeletotonClientProductGrid.jsx
  app/ui/socialLinks/SocialLinks.jsx
  app/ui/svg/BagNavIcon.jsx
  app/ui/svg/Burger.jsx
Labels: enhancement

#90 Tg/contact notification
  .env.example
  app/[lang]/auth/recovery/page.jsx
  app/lib/api/notifyInstance.js
  app/ui/contactForm/ContactForm.jsx
Labels: enhancement

#91 fix: add try/catch when notifications send
  app/lib/api/notifyInstance.js
  app/ui/contactForm/ContactForm.jsx
Labels: fix

#92 fix: add redirection from auth routes via middleware if logged in
  app/lib/middlewares/middleware1.js
  app/ui/auth/ClientSideRedirection.jsx
Labels: fix

#94 fix: blog page skeleton
  app/[lang]/blog/loading.jsx
  app/[lang]/blog/page.jsx
  app/ui/skeletons/SkeletonBlog.jsx
Labels: fix

#95 Bag and favorites
  app/[lang]/catalog/[id]/(overview)/page.jsx
  app/[lang]/profile/favorites/page.jsx
  app/[lang]/providers.jsx
  app/lib/actions.js
  app/lib/api/createUserStorages.js
  app/lib/api/instance.js
  app/lib/api/profileInstance.js
  app/lib/authActions.js
  app/lib/hooks/useLocalBag.jsx
  app/ui/auth/ClientSideRedirection.jsx
  app/ui/auth/LoginForm.jsx
  app/ui/auth/RegisterForm.jsx
  app/ui/bag/Bag.jsx
  app/ui/header/headerWrapper/HeaderWrapper.jsx
  app/ui/header/toolBar/ToolBar.jsx
  app/ui/order/listProductToBuy/ListProductToBuy.jsx
  app/ui/productCard/ProductCard.jsx
  app/ui/productItem/ProductItem.jsx
  app/ui/productsGrid/productList/ProductList.jsx
  app/ui/singleProduct/Breadcrumb/Breadcrumb.jsx
  app/ui/singleProduct/FavBtn/FavBtn.jsx
  app/ui/singleProduct/SingleProduct.jsx
  app/ui/singleProduct/singleProductSlider/SingleProductSlider.jsx
  app/ui/submitButton/SubmitButton.jsx
  app/ui/svg/Star.jsx
Labels: enhancement, fix

#100 fix: locales for provider buttons
  app/[lang]/auth/login/page.jsx
  app/[lang]/auth/recovery/page.jsx
  app/[lang]/auth/register/page.jsx
  app/lib/locales/en.json
  app/lib/locales/he.json
  app/ui/order/isAccount/IsAccount.jsx
  app/ui/providerButton/ProviderButton.jsx
Labels: enhancement, fix

#101 feat: infinit scroll
  app/[lang]/catalog/abc
  app/[lang]/catalog/page.jsx
  app/lib/api/instance.js
  app/ui/productItem/ProductItem.jsx
  app/ui/productsGrid/ProductsGrid.jsx
  app/ui/productsGrid/productList/ProductList.jsx
Labels: enhancement

#103 feat: update catalog
  app/ui/footer/footerProductsList/FooterProductList.jsx
  app/ui/footer/footerWrapper/FooterWrapper.jsx
  app/ui/header/headerWrapper/HeaderWrapper.jsx
  app/ui/productsGrid/ProductsGrid.jsx
  app/ui/productsGrid/categoryMenu/CategoryMenu.jsx
  app/ui/productsGrid/filter/Filter.jsx
  app/ui/productsGrid/mobileFilterMenu/MobileFilterMenu.jsx
  app/ui/scrollToTopButton/ScrollToTopButton.jsx
  public/img/hero-bg.jpg
Labels: enhancement, fix

#107 feat: handle if token is expired
  app/[lang]/expired/page.jsx
  app/lib/api/profileInstance.js
  app/lib/authActions.js
  app/lib/middlewares/middleware1.js
  app/ui/auth/LoginForm.jsx
Labels: enhancement

#111 feat: improve atodetection of locale via middleware when rederecting
  app/[lang]/auth/login/page.jsx
  app/lib/actions.js
  app/lib/authActions.js
  app/lib/middlewares/middleware1.js
  app/lib/middlewares/middleware2.js
  app/ui/auth/LoginForm.jsx
  app/ui/auth/RegisterForm.jsx
  app/ui/localeSwitcher/LocaleSwitcher.jsx
  app/ui/logout/Logout.jsx
Labels: enhancement

#113 fix: typeErrors cant read status
  app/[lang]/expired/page.jsx
  app/lib/actions.js
  app/lib/api/profileInstance.js
  app/lib/utils/flattenAttributes.js
  app/ui/profile/deleteBtn/DeleteBtn.jsx
  app/ui/profile/forms/AddressForm.jsx
  app/ui/profile/forms/RessetPasswordForm.jsx
  app/ui/profile/forms/UserDetailsForm.jsx
Labels: fix

#115 fix: hover error on product card
  app/[lang]/profile/page.jsx
  app/ui/globals.css
  app/ui/order/listProductToBuy/productToBuy/productToBuy.jsx
  app/ui/productCard/ProductCard.jsx
  app/ui/profile/AddressSection.jsx
Labels: fix

#116 refactor: about page features section
  app/ui/features/Features.jsx
Labels: refactor

#117 refactor: hero and slider on homePage
  app/[lang]/page.jsx
  app/lib/api/instance.js
  app/ui/catalogSlider/CatalogSlider.jsx
  app/ui/hero/Hero.jsx
Labels: refactor

#121 style: edit hero and about/features styles
  app/[lang]/about/page.jsx
  app/ui/about/About.jsx
  app/ui/button/Btn.jsx
  app/ui/catalogSlider/CatalogSlider.jsx
  app/ui/features/Features.jsx
  app/ui/hero/Hero.jsx
  app/ui/sectionWrapper/SectionWrapper.jsx
Labels: fix, refactor

#125 refactor: remove react-icons
  app/lib/actions.js
  app/ui/blogSlider/BlogSlider.jsx
  app/ui/contact/Contact.jsx
  app/ui/contactForm/ContactForm.jsx
  app/ui/modalContact/modalContacts/ModalContcats.jsx
  app/ui/modalContact/modalForm/ModalForm.jsx
  app/ui/modalWindow/ModalWindow.jsx
  app/ui/skeletons/SkeletonBlog.jsx
  app/ui/successSubmitMsg/SuccessSubmitMsg.jsx
  app/ui/svg/ArrowLeftIcon.jsx
  app/ui/svg/ArrowRightIcon.jsx
  app/ui/svg/AsteriskIcon.jsx
  app/ui/svg/PersonIcon.jsx
  app/ui/svg/QutersIcon.jsx
  app/ui/svg/SuccessIcon.jsx
  app/ui/svg/YoutubeIcon.jsx
  package.json
  yarn.lock
Labels: refactor

#129 fix: product item attributes
  app/[lang]/catalog/page.jsx
  app/[lang]/profile/favorites/page.jsx
  app/lib/api/profileInstance.js
  app/ui/catalogSlider/CatalogSlider.jsx
  app/ui/productItem/ProductItem.jsx
  app/ui/productsGrid/ProductsGrid.jsx
  app/ui/productsGrid/productList/ProductList.jsx
  app/ui/profile/favoritesContent/FavoritesContent.jsx
  app/ui/singleProduct/singleProductSlider/SingleProductSlider.jsx
Labels: fix

#131 feat: call to auth popover on catalog item card
  app/[lang]/catalog/page.jsx
  app/lib/api/profileInstance.js
  app/ui/callToAuth/CallToAuth.jsx
  app/ui/productItem/ProductItem.jsx
  app/ui/productsGrid/ProductsGrid.jsx
  app/ui/productsGrid/productList/ProductList.jsx
  app/ui/providerButton/ProviderButton.jsx
  app/ui/svg/FbIcon.jsx
  app/ui/svg/GoogleIcon.jsx
  app/ui/svg/TelegramIcon.jsx
  public/img/customerPlaceholder.jpg
  public/img/gb.svg
  public/img/he.svg
Labels: feature

#133 feat: return user to google rederection begin rout, edit navigation b…
  app/[lang]/auth/login/page.jsx
  app/[lang]/auth/recovery/page.jsx
  app/[lang]/auth/register/page.jsx
  app/lib/locales/en.json
  app/lib/locales/he.json
  app/ui/auth/ClientSideRedirection.jsx
  app/ui/auth/LoginForm.jsx
  app/ui/providerButton/ProviderButton.jsx
  app/ui/svg/Google.jsx
  app/ui/svg/GoogleIcon.jsx
Labels: feature, refactor

#134 feat: update readme.md
  README.md
Labels: feature, refactor

#135 fix: locale pathname on favorite list item link
  app/ui/profile/favoritesContent/FavoritesContent.jsx
Labels: fix

#145 feat: callback redirection after auth from order and catalog
  app/lib/api/auth.js
  app/lib/authActions.js
  app/lib/locales/en.json
  app/ui/auth/LoginForm.jsx
  app/ui/auth/RegisterForm.jsx
  app/ui/callToAuth/CallToAuth.jsx
  app/ui/order/isAccount/IsAccount.jsx
  app/ui/providerButton/ProviderButton.jsx
Labels: feature

#151 feat: fetch function on modal close
  app/lib/api/profileInstance.js
  app/lib/authActions.js
  app/ui/auth/ClientSideRedirection.jsx
  app/ui/auth/RegisterForm.jsx
  app/ui/bag/Bag.jsx
  app/ui/header/headerWrapper/HeaderWrapper.jsx
  app/ui/header/toolBar/ToolBar.jsx
  app/ui/singleProduct/Counter/Counter.jsx
  app/ui/singleProduct/SingleProduct.jsx
Labels: fix, refactor

#153 refactor: refactor code
  app/lib/actions.js
  app/lib/api/profileInstance.js
  app/lib/authActions.js
  app/ui/auth/ClientSideRedirection.jsx
  app/ui/bag/Bag.jsx
  app/ui/callToAuth/CallToAuth.jsx
  app/ui/globals.css
  app/ui/header/headerWrapper/HeaderWrapper.jsx
  app/ui/header/mobileMenu/MobileMenu.jsx
  app/ui/header/toolBar/ToolBar.jsx
  app/ui/logout/Logout.jsx
  app/ui/productItem/ProductItem.jsx
  app/ui/productsGrid/searchInCatalog/SearchInCatalog.jsx
  app/ui/providerButton/ProviderButton.jsx
  app/ui/search/filteredProduct/FilteredProduct.jsx
  app/ui/singleProduct/Breadcrumb/Breadcrumb.jsx
Labels: refactor

#156 refactor: errors unique messages
  app/lib/actions.js
  app/lib/api/instance.js
  app/lib/api/notifyInstance.js
  app/lib/api/profileInstance.js
  app/lib/authActions.js
  app/lib/orderActions.js
  app/ui/auth/ClientSideRedirection.jsx
  app/ui/bag/Bag.jsx
  app/ui/contactForm/ContactForm.jsx
  app/ui/header/toolBar/ToolBar.jsx
  app/ui/modalContact/modalForm/ModalForm.jsx
  app/ui/order/contactInfo/ContactInfo.jsx
  app/ui/order/isAccount/IsAccount.jsx
  app/ui/order/listProductToBuy/ListProductToBuy.jsx
  app/ui/productsGrid/ProductsGrid.jsx
  app/ui/singleProduct/SingleProduct.jsx
Labels: refactor

#157 refactor: additional trow error message
  app/lib/api/profileInstance.js
Labels: refactor

#161 feat: order history skeleton
  app/[lang]/profile/history-of-ordres/page.jsx
  app/[lang]/profile/page.jsx
  app/lib/api/profileInstance.js
  app/lib/locales/en.json
  app/lib/locales/he.json
  app/lib/middlewares/middleware1.js
  app/ui/header/toolBar/ToolBar.jsx
  app/ui/profile/favoritesContent/FavoritesContent.jsx
  app/ui/profile/forms/AddressForm.jsx
  app/ui/profile/orderHistory/OrderHistory.jsx
  app/ui/profile/orderHistory/SsrOrderHistory.jsx
  app/ui/skeletons/SkeletonOrderHistory.jsx
Labels: feature

#169 fix: locales on cta popover
  app/lib/locales/en.json
  app/lib/locales/he.json
  app/ui/callToAuth/CallToAuth.jsx
  app/ui/productItem/ProductItem.jsx
  app/ui/productsGrid/ProductsGrid.jsx
  app/ui/productsGrid/productList/ProductList.jsx
Labels: fix

#175 feat: show/hide pass button on password inputs
  app/ui/auth/LoginForm.jsx
  app/ui/auth/RegisterForm.jsx
  app/ui/auth/ResetPasswordForm.jsx
Labels: feature
